export enum AuditAction {
  // User Management
  USER_CREATED = 'USER_CREATED',
  USER_UPDATED = 'USER_UPDATED',
  USER_DELETED = 'USER_DELETED',
  USER_ACTIVATED = 'USER_ACTIVATED',
  USER_DEACTIVATED = 'USER_DEACTIVATED',
  PASSWORD_CHANGED = 'PASSWORD_CHANGED',
  PASSWORD_RESET = 'PASSWORD_RESET',

  // Authentication
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  LOGIN_FAILED = 'LOGIN_FAILED',
  LOGOUT = 'LOGOUT',

  // Trial Management
  TRIAL_CREATED = 'TRIAL_CREATED',
  TRIAL_UPDATED = 'TRIAL_UPDATED',
  TRIAL_DELETED = 'TRIAL_DELETED',

  // Reading Operations
  READING_CREATED = 'READING_CREATED',
  READING_UPDATED = 'READING_UPDATED',
  READING_APPROVED = 'READING_APPROVED',
  READING_REJECTED = 'READING_REJECTED',

  // Role/Permission Changes
  ROLE_CREATED = 'ROLE_CREATED',
  ROLE_UPDATED = 'ROLE_UPDATED',
  ROLE_DELETED = 'ROLE_DELETED',
  ROLE_LISTED = 'ROLE_LISTED',
  ROLE_ASSIGNED = 'ROLE_ASSIGNED',
  ROLE_REVOKED = 'ROLE_REVOKED',
  PERMISSION_CREATED = 'PERMISSION_CREATED',
  PERMISSION_UPDATED = 'PERMISSION_UPDATED',
  PERMISSION_DELETED = 'PERMISSION_DELETED',
  PERMISSION_GRANTED = 'PERMISSION_GRANTED',
  PERMISSION_REVOKED = 'PERMISSION_REVOKED',
}

export enum EntityType {
  USER = 'User',
  TRIAL = 'Trial',
  READING = 'Reading',
  PLOT = 'Plot',
  VARIETY = 'Variety',
  LOCATION = 'Location',
  ROLE = 'Role',
  PERMISSION = 'Permission',
}
